### PR TITLE
Use Micronaut AOT

### PR DESCRIPTION
**Pull request by alvarosanchez**
This PR introduces [Micronaut AOT](https://micronaut-projects.github.io/micronaut-aot/latest/guide/) to the build. It is done in a way so that the commands used to run in dev mode and package the native image are the same.

### CODE REVIEW

**Comment by mraible** [comment]
Thanks for your contribution, @alvarosanchez! 

I'm curious, why aren't these settings automatically configured when I include `-f micronaut-aot` when creating the app? 

Adding the code from this PR to the [Make a Micronaut App from Scratch](https://developer.okta.com/blog/2021/06/18/native-java-framework-comparison#make-a-micronaut-app-from-scratch) section of the blog post will make Micronaut's AOT look pretty complicated, IMO.

**Comment by alvarosanchez** [comment]
> I'm curious, why aren't these settings automatically configured when I include -f micronaut-aot when creating the app?

They will soon, I'm working on that. I just wanted to gather some general feedback from you here.

**Comment by alvarosanchez** [comment]
Done in https://corparch-core-srv.slack.com/archives/D039E106PHA/p1648652672075089

Will be ready by next week with Micronaut 3.4.2.

**Comment by mraible** [comment]
@alvarosanchez Great! I'll make sure this repo and its blog post are updated shortly after it's released and before my talk at Devoxx France (April 21).

**Comment by mraible** [comment]
@alvarosanchez I created a new Micronaut app using the following command:

```
mn create-app com.okta.rest.app --build maven -f security-jwt -f micronaut-aot
```

You can see the results of what changed between Micronaut 3.4.0 and 3.4.2 in #22. It doesn't seem to have all the changes that are in this PR. Is that expected?

**Comment by mraible** [comment]
@alvarosanchez The generated app in #22 works fine when I run `./mvnw mn:run` but fails to build with GraalVM afterward using `./mvnw package -Dpackaging=native-image`. If I run `./mvnw clean` before `package`, it works fine. 

I wanted to let you know about this because this behavior is different from previous versions. 

```
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< com.okta.rest:app >--------------------------
[INFO] Building app 0.1
[INFO] ----------------------------[ native-image ]----------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ app ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- micronaut-maven-plugin:3.2.3:aot-analysis (default-aot-analysis) @ app ---
[WARNING] Packaging is set to [native-image], but Micronaut AOT runtime is set to [jit]. Setting AOT runtime to: [native]
[INFO] Running Micronaut AOT 1.0.3 aot-analysis
[INFO] Packaging project
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 2 resources
[INFO] Nothing to compile - all classes are up to date
[INFO] Executing Micronaut AOT analysis
22:15:51.159 [main] INFO  i.m.aot.MicronautAotOptimizer - Analysis will be performed with active environments: []
[INFO]
[INFO] --- micronaut-maven-plugin:3.2.3:graalvm-resources (default-graalvm-resources) @ app ---
[INFO] Generating /Users/mraible/Downloads/micronaut/target/classes/META-INF/native-image/com.okta.rest/app/resource-config.json
[INFO]
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ app ---
[INFO] Building jar: /Users/mraible/Downloads/micronaut/target/app-0.1.jar
[INFO]
[INFO] --- native-maven-plugin:0.9.11:build (default-build) @ app ---
[INFO] ImageClasspath Entry: io.micronaut:micronaut-inject:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-inject/3.4.2/micronaut-inject-3.4.2.jar)
[INFO] ImageClasspath Entry: org.slf4j:slf4j-api:jar:1.7.29:compile (file:///Users/mraible/.m2/repository/org/slf4j/slf4j-api/1.7.29/slf4j-api-1.7.29.jar)
[INFO] ImageClasspath Entry: javax.annotation:javax.annotation-api:jar:1.3.2:compile (file:///Users/mraible/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar)
[INFO] ImageClasspath Entry: jakarta.inject:jakarta.inject-api:jar:2.0.1:compile (file:///Users/mraible/.m2/repository/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-core:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-core/3.4.2/micronaut-core-3.4.2.jar)
[INFO] ImageClasspath Entry: org.yaml:snakeyaml:jar:1.30:compile (file:///Users/mraible/.m2/repository/org/yaml/snakeyaml/1.30/snakeyaml-1.30.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-validation:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-validation/3.4.2/micronaut-validation-3.4.2.jar)
[WARNING] jar:file:///Users/mraible/.m2/repository/io/micronaut/micronaut-validation/3.4.2/micronaut-validation-3.4.2.jar!/META-INF/native-image/io.micronaut.validation/micronaut-validation/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.micronaut:micronaut-core-reactive:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-core-reactive/3.4.2/micronaut-core-reactive-3.4.2.jar)
[INFO] ImageClasspath Entry: org.reactivestreams:reactive-streams:jar:1.0.3:compile (file:///Users/mraible/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar)
[INFO] ImageClasspath Entry: javax.validation:validation-api:jar:2.0.1.Final:compile (file:///Users/mraible/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar)
[INFO] ImageClasspath Entry: io.projectreactor:reactor-core:jar:3.4.14:runtime (file:///Users/mraible/.m2/repository/io/projectreactor/reactor-core/3.4.14/reactor-core-3.4.14.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-http-client:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-http-client/3.4.2/micronaut-http-client-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-http-client-core:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-http-client-core/3.4.2/micronaut-http-client-core-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-websocket:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-websocket/3.4.2/micronaut-websocket-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-http-netty:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-http-netty/3.4.2/micronaut-http-netty-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-buffer-netty:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-buffer-netty/3.4.2/micronaut-buffer-netty-3.4.2.jar)
[INFO] ImageClasspath Entry: io.netty:netty-codec-http2:jar:4.1.76.Final:compile (file:///Users/mraible/.m2/repository/io/netty/netty-codec-http2/4.1.76.Final/netty-codec-http2-4.1.76.Final.jar)
[WARNING] jar:file:///Users/mraible/.m2/repository/io/netty/netty-codec-http2/4.1.76.Final/netty-codec-http2-4.1.76.Final.jar!/META-INF/native-image/io.netty/codec-http2/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.netty:netty-handler:jar:4.1.76.Final:compile (file:///Users/mraible/.m2/repository/io/netty/netty-handler/4.1.76.Final/netty-handler-4.1.76.Final.jar)
[WARNING] jar:file:///Users/mraible/.m2/repository/io/netty/netty-handler/4.1.76.Final/netty-handler-4.1.76.Final.jar!/META-INF/native-image/io.netty/handler/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.netty:netty-resolver:jar:4.1.76.Final:compile (file:///Users/mraible/.m2/repository/io/netty/netty-resolver/4.1.76.Final/netty-resolver-4.1.76.Final.jar)
[INFO] ImageClasspath Entry: io.netty:netty-handler-proxy:jar:4.1.76.Final:compile (file:///Users/mraible/.m2/repository/io/netty/netty-handler-proxy/4.1.76.Final/netty-handler-proxy-4.1.76.Final.jar)
[INFO] ImageClasspath Entry: io.netty:netty-common:jar:4.1.76.Final:compile (file:///Users/mraible/.m2/repository/io/netty/netty-common/4.1.76.Final/netty-common-4.1.76.Final.jar)
[WARNING] jar:file:///Users/mraible/.m2/repository/io/netty/netty-common/4.1.76.Final/netty-common-4.1.76.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.netty:netty-buffer:jar:4.1.76.Final:compile (file:///Users/mraible/.m2/repository/io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.jar)
[WARNING] jar:file:///Users/mraible/.m2/repository/io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.netty:netty-transport:jar:4.1.76.Final:compile (file:///Users/mraible/.m2/repository/io/netty/netty-transport/4.1.76.Final/netty-transport-4.1.76.Final.jar)
[WARNING] jar:file:///Users/mraible/.m2/repository/io/netty/netty-transport/4.1.76.Final/netty-transport-4.1.76.Final.jar!/META-INF/native-image/io.netty/transport/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.netty:netty-codec:jar:4.1.76.Final:compile (file:///Users/mraible/.m2/repository/io/netty/netty-codec/4.1.76.Final/netty-codec-4.1.76.Final.jar)
[INFO] ImageClasspath Entry: io.netty:netty-codec-socks:jar:4.1.76.Final:compile (file:///Users/mraible/.m2/repository/io/netty/netty-codec-socks/4.1.76.Final/netty-codec-socks-4.1.76.Final.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-http-server-netty:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-http-server-netty/3.4.2/micronaut-http-server-netty-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-http-server:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-http-server/3.4.2/micronaut-http-server-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-router:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-router/3.4.2/micronaut-router-3.4.2.jar)
[INFO] ImageClasspath Entry: io.netty:netty-codec-http:jar:4.1.76.Final:compile (file:///Users/mraible/.m2/repository/io/netty/netty-codec-http/4.1.76.Final/netty-codec-http-4.1.76.Final.jar)
[WARNING] jar:file:///Users/mraible/.m2/repository/io/netty/netty-codec-http/4.1.76.Final/netty-codec-http-4.1.76.Final.jar!/META-INF/native-image/io.netty/codec-http/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.micronaut:micronaut-jackson-databind:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-jackson-databind/3.4.2/micronaut-jackson-databind-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-jackson-core:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-jackson-core/3.4.2/micronaut-jackson-core-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-json-core:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-json-core/3.4.2/micronaut-json-core-3.4.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-core:jar:2.13.2:compile (file:///Users/mraible/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.13.2/jackson-core-2.13.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-annotations:jar:2.13.2:compile (file:///Users/mraible/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.13.2/jackson-annotations-2.13.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-databind:jar:2.13.2.2:compile (file:///Users/mraible/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.2:compile (file:///Users/mraible/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.13.2/jackson-datatype-jdk8-2.13.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.2:compile (file:///Users/mraible/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.2/jackson-datatype-jsr310-2.13.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-runtime:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-runtime/3.4.2/micronaut-runtime-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-http:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-http/3.4.2/micronaut-http-3.4.2.jar)
[WARNING] jar:file:///Users/mraible/.m2/repository/io/micronaut/micronaut-http/3.4.2/micronaut-http-3.4.2.jar!/META-INF/native-image/io.micronaut.http/micronaut-http/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.micronaut:micronaut-aop:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-aop/3.4.2/micronaut-aop-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut:micronaut-context:jar:3.4.2:compile (file:///Users/mraible/.m2/repository/io/micronaut/micronaut-context/3.4.2/micronaut-context-3.4.2.jar)
[INFO] ImageClasspath Entry: io.micronaut.security:micronaut-security-jwt:jar:3.5.0:compile (file:///Users/mraible/.m2/repository/io/micronaut/security/micronaut-security-jwt/3.5.0/micronaut-security-jwt-3.5.0.jar)
[WARNING] jar:file:///Users/mraible/.m2/repository/io/micronaut/security/micronaut-security-jwt/3.5.0/micronaut-security-jwt-3.5.0.jar!/META-INF/native-image/io.micronaut.security/token-jwt/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: io.micronaut.security:micronaut-security:jar:3.5.0:compile (file:///Users/mraible/.m2/repository/io/micronaut/security/micronaut-security/3.5.0/micronaut-security-3.5.0.jar)
[INFO] ImageClasspath Entry: io.micronaut.security:micronaut-security-annotations:jar:3.5.0:compile (file:///Users/mraible/.m2/repository/io/micronaut/security/micronaut-security-annotations/3.5.0/micronaut-security-annotations-3.5.0.jar)
[INFO] ImageClasspath Entry: com.nimbusds:nimbus-jose-jwt:jar:9.20:compile (file:///Users/mraible/.m2/repository/com/nimbusds/nimbus-jose-jwt/9.20/nimbus-jose-jwt-9.20.jar)
[INFO] ImageClasspath Entry: com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile (file:///Users/mraible/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar)
[INFO] ImageClasspath Entry: jakarta.annotation:jakarta.annotation-api:jar:2.0.0:compile (file:///Users/mraible/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.0.0/jakarta.annotation-api-2.0.0.jar)
[INFO] ImageClasspath Entry: ch.qos.logback:logback-classic:jar:1.2.10:runtime (file:///Users/mraible/.m2/repository/ch/qos/logback/logback-classic/1.2.10/logback-classic-1.2.10.jar)
[INFO] ImageClasspath Entry: ch.qos.logback:logback-core:jar:1.2.10:runtime (file:///Users/mraible/.m2/repository/ch/qos/logback/logback-core/1.2.10/logback-core-1.2.10.jar)
[INFO] ImageClasspath Entry: com.okta.rest:app:native-image:0.1 (file:///Users/mraible/Downloads/micronaut/target/app-0.1.jar)
[INFO] Executing: /Users/mraible/.sdkman/candidates/java/current/bin/native-image @/var/folders/f7/5x4rvsr5599ffnfckn487nzm0000gn/T/native-image10219684773485556230args
========================================================================================================================
GraalVM Native Image: Generating 'app'...
========================================================================================================================
[1/7] Initializing...                                                                                    (4.2s @ 0.24GB)
 Version info: 'GraalVM 22.0.0.2 Java 17 CE'
 3 user-provided feature(s)
  - io.micronaut.buffer.netty.NettyFeature
  - io.micronaut.http.netty.graal.HttpNettyFeature
  - io.micronaut.jackson.JacksonDatabindFeature
[2/7] Performing analysis...  []                                                                         (6.6s @ 0.53GB)
To see how the classes got initialized, use --trace-class-initialization=com.okta.rest.aot.generated.PropertySourceLoaderFactory,com.okta.rest.aot.generated.HttpResponseFactoryFactory,com.okta.rest.aot.generated.BeanIntrospectionReferenceFactory,com.okta.rest.aot.generated.BeanDefinitionReferenceFactory,com.okta.rest.aot.generated.BeanConfigurationFactory,com.okta.rest.aot.generated.HttpRequestFactoryFactory
   4,219 (87.53%) of  4,820 classes reachable
   5,345 (63.05%) of  8,478 fields reachable
  18,084 (79.86%) of 22,644 methods reachable
      55 classes,   124 fields, and   866 methods registered for reflection

Error: Classes that should be initialized at run time got initialized during image building:
 com.okta.rest.aot.generated.PropertySourceLoaderFactory was unintentionally initialized at build time. To see why com.okta.rest.aot.generated.PropertySourceLoaderFactory got initialized use --trace-class-initialization=com.okta.rest.aot.generated.PropertySourceLoaderFactory
com.okta.rest.aot.generated.HttpResponseFactoryFactory was unintentionally initialized at build time. To see why com.okta.rest.aot.generated.HttpResponseFactoryFactory got initialized use --trace-class-initialization=com.okta.rest.aot.generated.HttpResponseFactoryFactory
com.okta.rest.aot.generated.BeanIntrospectionReferenceFactory was unintentionally initialized at build time. To see why com.okta.rest.aot.generated.BeanIntrospectionReferenceFactory got initialized use --trace-class-initialization=com.okta.rest.aot.generated.BeanIntrospectionReferenceFactory
com.okta.rest.aot.generated.BeanDefinitionReferenceFactory was unintentionally initialized at build time. To see why com.okta.rest.aot.generated.BeanDefinitionReferenceFactory got initialized use --trace-class-initialization=com.okta.rest.aot.generated.BeanDefinitionReferenceFactory
com.okta.rest.aot.generated.BeanConfigurationFactory was unintentionally initialized at build time. To see why com.okta.rest.aot.generated.BeanConfigurationFactory got initialized use --trace-class-initialization=com.okta.rest.aot.generated.BeanConfigurationFactory
com.okta.rest.aot.generated.HttpRequestFactoryFactory was unintentionally initialized at build time. To see why com.okta.rest.aot.generated.HttpRequestFactoryFactory got initialized use --trace-class-initialization=com.okta.rest.aot.generated.HttpRequestFactoryFactory

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
------------------------------------------------------------------------------------------------------------------------
                        0.4s (3.5% of total time) in 17 GCs | Peak RSS: 2.09GB | CPU load: 10.27
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /Users/mraible/Downloads/micronaut/target/app.build_artifacts.txt
========================================================================================================================
Failed generating 'app' after 11.0s.
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.673 s
[INFO] Finished at: 2022-04-16T22:16:03-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.11:build (default-build) on project app: Execution of /Users/mraible/.sdkman/candidates/java/current/bin/native-image @/var/folders/f7/5x4rvsr5599ffnfckn487nzm0000gn/T/native-image10219684773485556230args returned non-zero result -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by alvarosanchez** [comment]
> It doesn't seem to have all the changes that are in this PR. Is that expected?

The only bit missing AFAIK is the Logback XML to Java conversion, which requires Logback 1.3 which is still an alpha version.

**Comment by mraible** [comment]
Thanks for the response @alvarosanchez. I'll close this issue. I documented the need to run `clean` in my post's update PR. https://github.com/oktadev/okta-blog/pull/1142

**Comment by alvarosanchez** [comment]
Sounds good. I have created an issue to track down the error, since running clean is not optimal.

Will send a PR to the blog once that is fixed.

**Pull request closed without merging**
