### PR TITLE
Upgrade to Micronaut 3.3 and Micronaut AOT

### PR DESCRIPTION
**Pull request by melix**
Hi @mraible!

This pull request implements 2 improvements:

- first it upgrades the Micronaut 3.3, which was just out
- then it integrates with [Micronaut AOT](https://medium.com/graalvm/introducing-micronaut-aot-build-time-optimizations-for-your-micronaut-applications-68b8f1302c5)

For the purpose, I had to change the build so that it uses Gradle, not Maven (because Micronaut AOT isn't supported in Maven yet).

If you look at the 2d commit message, you'll see that I explain how the integration with AOT is transparent to your measurements: you can still use `./gradlew run` or `./gradlew nativeCompile` like you used to, there are simply now more options.

In particular, you'll be interested in starting the native, AOT optimized version of the application:

    ./gradlew nativeOptimizedRun

Tested locally and works great for me :)

### CODE REVIEW

**Comment by mraible** [comment]
Hello @melix! Thanks for the optimization. 

Is it possible to create this app using the `mn` command? The related blog post has a [Make a Micronaut App from Scratch](https://developer.okta.com/blog/2021/06/18/native-java-framework-comparison#make-a-micronaut-app-from-scratch) section that will need to be updated after this is merged. 

Also, I used Maven on purpose since that's what Quarkus and Spring Boot do by default.

**Comment by melix** [comment]
> Is it possible to create this app using the mn command? The related blog post has a Make a Micronaut App from Scratch section that will need to be updated after this is merged.

You can add the `micronaut-aot` feature starting from Micronaut 3.3.0. E.g:

    mn create-app com.okta.rest.app -f security-jwt -f micronaut-aot

Note that it would use M6, but M7 has been released since then. Also since AOT features are opt-in, it wouldn't enable the logback conversion like in my PR.

> Also, I used Maven on purpose since that's what Quarkus and Spring Boot do by default.

I understand but IMO makes not much sense: Micronaut defaults to Gradle and has significantly better UX with Gradle :)

**Comment by mraible** [comment]
> For the purpose, I had to change the build so that it uses Gradle, not Maven (because Micronaut AOT isn't supported in Maven yet).

@melix Is Micronaut AOT supported by Maven yet? I don't feel like I'm comparing apples-to-apples if I use Gradle with Micronaut and Maven with the other frameworks. And, I don't want to change all frameworks to use Gradle.

**Comment by melix** [comment]
FYI [Micronaut 3.4.1](https://github.com/micronaut-projects/micronaut-core/releases/tag/v3.4.1) has just been released.

> @melix Is Micronaut AOT supported by Maven yet?

You can with the [Maven Plugin](https://micronaut-projects.github.io/micronaut-maven-plugin/latest/examples/aot.html) since last week.

>  I don't feel like I'm comparing apples-to-apples if I use Gradle with Micronaut and Maven with the other frameworks

IMHO this is mostly irrelevant: the build tool has no impact on runtime. It has an impact on developer UX (which is better with Gradle+Micronaut). In any case I wouldn't recommend to use Maven but your choice :)

**Comment by mraible** [comment]
Closing in favor of #16 so all updates are in one PR. You can see the blog post updates in https://github.com/oktadev/okta-blog/pull/1123.

**Pull request closed without merging**
